### ISSUE TITLE
Facebook share sheet auto-dismisses 

### ISSUE THREAD

**Issue by langford** [Bernie-2016/fieldthebern-ios#103] opened 2016-01-20 08:26 UTC
To reproduce: 

Uninstall FB Native App (not sure if this is required)

Start FtB app

Tap Learn

Tap Bernie on the Issues

Tap Economic Equality

Tap the share icon

Tap Facebook

wait approximately 5 seconds, sheet will disappear

**Comment by dedual** [comment] 2016-02-05 18:36
Duplicate of #104 . Closing this one.

**Closed by dedual** 2016-02-05 18:36 UTC
