### ISSUE TITLE
Autolayout issue with iOS 4

### ISSUE THREAD

**Issue by JoshSmith** [Bernie-2016/fieldthebern-ios#87] opened 2016-01-05 00:40 UTC
You can see in the screenshot below some odd issues with autolayout.

![http://imgur.com/kYuEsqO](http://i.imgur.com/kYuEsqO.jpg)

**Comment by yar1vn** [comment] 2016-01-14 07:02
![simulator screen shot jan 13 2016 23 01 48](https://cloud.githubusercontent.com/assets/2396893/12317827/a8d0472c-ba49-11e5-999b-eb5697738a4f.png)

Tested on iPhone 4S, looks good. Is that still an issue?

**Comment by yar1vn** [comment] 2016-01-14 07:04
![simulator screen shot jan 13 2016 23 04 08](https://cloud.githubusercontent.com/assets/2396893/12317854/f2102ec0-ba49-11e5-98a5-3db14102041a.png)

**Comment by yar1vn** [comment] 2016-01-14 07:45
Cannot reproduce, closing for now

**Closed by yar1vn** 2016-01-14 07:45 UTC
Labels: bug
